### ISSUE TITLE
Create an own inclusion standard

### ISSUE THREAD

**Issue by Croydon** [inexor-game/data#11]
Explain in a wiki page what standards content (maps, sounds, skyboxes..) have to accomplish to get offical content (besides the license policy of course). For a reference: http://quadropolis.us/node/3186

Pad: https://pad.inexor.org/p/Inexor_Inclusion_Standard

**Comment by aschaeffer** [comment]
:+1:

**Comment by aschaeffer** [comment]
* Textures should be of high quality (min 1024px), downscaling is always possible
* Textures should always contain mipmaps (see http://en.wikipedia.org/wiki/Mipmap)
* Textures should contain a heightmaps
* Textures should be reusable on different maps
* Models should be optimized for few polygons for performance reasons

**Comment by koraa** [comment]
We might consider providing a system to maintain multiple versions of a model with different quality.

**Comment by aschaeffer** [comment]
:+1:

We discussed the same topic for textures yesterday:

* user can set the texture quality in the settings
* the texture downloading mechanism only fetches the textures in the required quality (-> so we can save a lot of bandwidth)

**Comment by Croydon** [comment]
Updated pad to https://pad.inexor.org/p/Inexor_Inclusion_Standard

**Comment by a-teammate** [comment]
Actually we do not need the point
* ~~Textures should always contain mipmaps (see http://en.wikipedia.org/wiki/Mipmap)~~
since they can get generated.
