### ISSUE TITLE
Create an instructional beginner map with audio playbacks

### ISSUE THREAD

**Issue by Croydon** [inexor-game/data#18]
From @IAmNotHanni in [code/#75](https://github.com/inexor-game/code/issues/75):

> Maybe we could script a beginner map with audio playbacks. I am inspired by Portal in this aspect:
https://youtu.be/eFe3eKaKeF0?t=59s
> 
> This would be so awesome!

**Comment by Fohlen** [comment]
This issue was moved to inexor-game/code#257
