### ISSUE TITLE
Voice Acting

### ISSUE THREAD

**Issue by aschaeffer** [inexor-game/data#9]
Recording voice samples: Killing Spree, ...

Voice: TOMYC
Ideas: @movabo

**Comment by ObaniGemini** [comment]
Do the old sounds need to be made also? (e.g: quad_damage annoucements,etc...)

**Comment by Croydon** [comment]
@ObaniGemini I will soon contact the creator (or one of them not sure without looking in it)  and ask for relicensing (he made also other kind of content). If he is up for relicensing we wouldn't need replacement, but for some reason I doubt that he will agree.

**Comment by Fohlen** [comment]
This issue was moved to inexor-game/code#255
